import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  extendTheme,
  ChakraProvider,
  Container,
  Grid,
  GridItem,
} from "@chakra-ui/react";
import React, { useState } from "react";
import { createUseStyles } from "react-jss";
import Sidebar from "../components/Sidebar";

const useStyles = createUseStyles({
  main: {
    display: "flex",
  },
  content: {
    width: "100%",
    "@media screen and (max-width: 1000px)": {
      marginLeft: "0",
    },
  },
});

export default function Home() {
  const classes = useStyles();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <div className={classes.content}>
          {/* <Switch>
              <Route path="/wordfinder">
                <WordFinder />
              </Route>
              <Route path="/excelreader">
                <ExcelReader />
              </Route>
            </Switch> */}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
